version: 0.0
os: linux

files:
  - source: /  # This is the folder inside the zip
    destination: /new_chatapp  # This is where the content should be deployed on the server

hooks:
  BeforeInstall:
    - location: scripts/sync_chatapp.sh
      runas: chatapp

  AfterInstall:
    - location: scripts/activate_venv_and_install_requirements.sh
      runas: chatapp

  ApplicationStart:
    - location: scripts/migrate_and_restart_django.sh
      runas: chatapp
