version: 0.0
os: linux

files:
  - source: /
    destination: /new_chatapp
    file_exists_behavior: OVERWRITE  # Ensure files get replaced

hooks:
  ApplicationStart:
    - location: scripts/migrate_and_restart_django.sh
      runas: chatapp
